CREATE TABLE IF NOT EXISTS Users(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Login TEXT NOT NULL,
    Password TEXT NOT NULL,
    Latitude REAL,
    Longitude REAL
);

CREATE TABLE IF NOT EXISTS Points(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    Latitude REAL NOT NULL,
    Longitude REAL NOT NULL
);