# Generated by Django 3.2.16 on 2022-10-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='Rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='Latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='Longitude',
            field=models.FloatField(default=0),
        ),
    ]
